# Nombre de la pipeline
name: Deploy Angular App to Azure

# Configura los disparadores.
# Solo se ejecutar√° cuando se haga un push o pull request a la rama 'deploy-azure'
on:
  push:
    branches:
      - deploy-azure
  pull_request:
    branches:
      - deploy-azure

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --force

      - name: Run unit tests
        run: ng test --no-watch  --browsers=ChromeHeadless

      - name: Build Angular app
        run: ng build

      - name: Deploy to Azure Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN }}
          app_location: "/dist/my-first-project"
          deployment_action: "upload"